services:
  traefik:
    restart: unless-stopped
    image: traefik:v2.4

    container_name: ${PROJECT_NAME}_TRAEFIK
    ports:
      - "80:80"
      - "443:443"
    labels:
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      # Dashboard
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`dashboard.traefik.me`)"
      - "traefik.http.routers.dashboard-tls.tls.domains[0].main=dashboard.traefik.me"
      - "traefik.http.routers.dashboard-tls.tls.domains[0].sans=dashboard-*.traefik.me"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.traefik.service=api@internal"

      # htaccess password
      # - "traefik.http.routers.traefik.middlewares=auth"
      # - "traefik.http.middlewares.auth.basicauth.users=user:$$apr1$$q8eZFHjF$$Fvmkk//V6Btlaf2i/ju5n/" # user/password
    volumes:
      - ./.docker/traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./.docker/traefik/tls.yml:/etc/traefik/tls.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - certs:/etc/ssl/traefik

    networks:
      - dev

  reverse-proxy-https-helper:
    image: alpine
    container_name: ${PROJECT_NAME}_PROXY_HELPER
    command: sh -c "cd /etc/ssl/traefik
      && wget traefik.me/cert.pem -O cert.pem
      && wget traefik.me/privkey.pem -O privkey.pem"
    volumes:
      - certs:/etc/ssl/traefik
    networks:
      - dev

volumes:
  certs:

networks:
  dev:
    external: true
